[package]
name = "helm-templexer"
version = "0.1.0"
authors = ["Hendrik Maus <aidentailor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.15"
structopt-flags = "0.3.5"
log = "0.4.8"
env_logger = "0.7.1"
anyhow = "1.0.31"
thiserror = "1.0.20"
serde_any = "0.5.0"
serde = "1.0.114"
subprocess = "0.2.4"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
pretty_assertions = "0.6.1"
