[package]
name = "helm-templexer"
version = "0.1.1-alpha"
authors = ["Hendrik Maus <aidentailor@gmail.com>"]
edition = "2018"

description = "Render Kubernetes Helm charts for multiple environments with _explicit config_ while keeping the overhead at ease"
license = "MIT"
keywords = ["kubernetes", "helm"]
readme = "README.md"
categories = ["command-line-utilities"]

[[bin]]
name = "helm-templexer"
path = "src/main.rs"
doc = false

[dependencies]
structopt = "0.3.20"
structopt-flags = "0.3.6"
log = "0.4.11"
env_logger = "0.8.1"
anyhow = "1.0.34"
thiserror = "1.0.22"
serde_any = "0.5.0"
serde = "1.0.117"
subprocess = "0.2.6"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
pretty_assertions = "0.6.1"
