[package]
name = "helm-templexer"
version = "0.1.0"
authors = ["Hendrik Maus <hendrik.maus@trivago.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.15"
structopt-flags = "0.3.5"
log = "0.4.8"
env_logger = "0.7.1"
