name: Build

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch:
          - aarch64
          - x86_64
        os:
          - unknown-linux-musl
          - apple-darwin
          - pc-windows-gnu
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.0
        with:
          RUSTTARGET: ${{ matrix.arch }}-$ {{ matrix.os }}
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
