name: Build

on:
  release:
    types:
      - published

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # arch:
        #   - aarch64
        #   - x86_64
        # os:
        #   - unknown-linux-musl
        #   - apple-darwin
        #   - pc-windows-gnu
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-apple-darwin
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../helm-templexer-${{ matrix.target }}.tar.gz helm-templexer
          cd -
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./helm-templexer-${{ matrix.target }}.tar.gz
          asset_name: helm-templexer-${{ matrix.target }}.tar.gz
          asset_content_type: application/gzip
